"""update role and permission unique constraints for multi-tenancy

Revision ID: 2567b3a91921
Revises: 854548818ce4
Create Date: 2025-11-24 21:12:45.209711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2567b3a91921'
down_revision = '854548818ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_permissions_name')
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('uq_permission_name_tenant', ['name', 'tenant_id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_name')
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('uq_role_name_tenant', ['name', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_name_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index('ix_roles_name', ['name'], unique=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_permission_name_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.create_index('ix_permissions_name', ['name'], unique=True)

    # ### end Alembic commands ###
