"""Make asset_id optional in maintenance requests

Revision ID: 5d2718d27c04
Revises: 2d89bcf84eed
Create Date: 2025-11-08 21:02:32.551382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2718d27c04'
down_revision = '2d89bcf84eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
