"""add tenants and tenant_subscriptions tables

Revision ID: 854548818ce4
Revises: 703647c40fdb
Create Date: 2025-11-19 12:56:30.550303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854548818ce4'
down_revision = '703647c40fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_assets', sa.Integer(), nullable=True),
    sa.Column('max_requests_per_month', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('trial_ends', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_subdomain'), ['subdomain'], unique=True)

    op.create_table('tenant_subscriptions',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('tenant_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_feature_flags_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_maintenance_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_permissions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_permissions_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feature_flags_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assets_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenant_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_subscriptions_tenant_id'))

    op.drop_table('tenant_subscriptions')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_subdomain'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
