"""Add category column to maintenance_requests

Revision ID: dca6cb0113e4
Revises: 5d2718d27c04
Create Date: 2025-11-08 23:12:56.784520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca6cb0113e4'
down_revision = '5d2718d27c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
