"""Add feature flags table

Revision ID: e9ec068cf628
Revises: dca6cb0113e4
Create Date: 2025-11-11 12:30:26.045100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ec068cf628'
down_revision = 'dca6cb0113e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ANALYTICS', 'NOTIFICATIONS', 'INTEGRATIONS', 'MOBILE', 'AUTOMATION', 'SECURITY', 'UI', 'EXPERIMENTAL', name='featurecategory'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flags_feature_key'), ['feature_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_feature_key'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_enabled'))

    op.drop_table('feature_flags')
    # ### end Alembic commands ###
